items = [
                  "Tomato",
                  "Black Gram (Urd Beans)(Whole)",
                  "Lemon",
                  "Jowar(Sorghum)",
                  "Bengal Gram(Gram)(Whole)",
                  "Paddy(Dhan)(Common)",
                  "Maize",
                  "Apple",
                  "Banana - Green",
                  "Bhindi(Ladies Finger)",
                  "Bitter Gourd",
                  "Bottle Gourd",
                  "Brinjal",
                  "Cabbage",
                  "Capsicum",
                  "Carrot",
                  "Cauliflower",
                  "Chikoos(Sapota)",
                  "Coriander(Leaves)",
                  "Cucumbar(Kheera)",
                  "Garlic",
                  "Ginger(Green)",
                  "Grapes",
                  "Green Chilli",
                  "Guar",
                  "Karbuja(Musk Melon)",
                  "Knool Khol",
                  "Little Gourd (Kundru)",
                  "Methi(Leaves)",
                  "Mousambi(Sweet Lime)",
                  "Onion",
                  "Orange",
                  "Papaya (Raw)",
                  "Peas Wet",
                  "Pomegranate",
                  "Potato",
                  "Pumpkin",
                  "Raddish",
                  "Sweet Potato",
                  "Tinda",
                  "Water Melon",
                  "Soyabean",
                  "Cotton",
                  "Cummin Seed(Jeera)",
                  "Groundnut",
                  "Sesamum(Sesame",
                  "Gingelly",
                  "Til)",
                  "Wheat",
                  "Arhar (Tur/Red Gram)(Whole)",
                  "Bajra(Pearl Millet/Cumbu)",
                  "Green Gram (Moong)(Whole)",
                  "Kabuli Chana(Chickpeas-White)",
                  "Methi Seeds",
                  "Mustard",
                  "Castor Seed",
                  "Guar Seed(Cluster Beans Seed)",
                  "Isabgul (Psyllium)",
                  "Onion Green",
                  "Corriander Seed",
                  "Dry Chillies",
                  "Ground Nut Seed",
                  "Cluster Beans",
                  "Beetroot",
                  "Cowpea(Veg)",
                  "Drumstick",
                  "Elephant Yam (Suran)",
                  "French Beans (Frasbean)",
                  "Indian Beans (Seam)",
                  "Pegeon Pea (Arhar Fali)",
                  "Pointed Gourd (Parval)",
                  "Ridge Gourd(Tori)",
                  "Surat Beans (Papadi)",
                  "Turmeric (Raw)",
                  "Yam (Ratalu)",
                  "Spinach",
                  "Banana",
                  "Ber(Zizyphus/Borehannu)",
                  "Ginger(Dry)",
                  "Guava",
                  "Kinnow",
                  "Turnip",
                  "Leafy Vegetable",
                  "Papaya",
                  "Peas Cod",
                  "Pineapple",
                  "Mashrooms",
                  "Colacasia",
                  "Field Pea",
                  "Dalda",
                  "Mahua",
                  "Mustard Oil",
                  "Rice",
                  "Sugar",
                  "Wheat Atta",
                  "White Peas",
                  "Beans",
                  "Chapparad Avare",
                  "Chilly Capsicum",
                  "Green Avare (w)",
                  "Seemebadnekai",
                  "Snake Gourd",
                  "Suvarna Gadde",
                  "Sweet Pumpkin",
                  "Kulthi(Horse Gram)",
                  "Bunch Beans",
                  "Thondekai",
                  "Tamarind Seed",
                  "Tamarind Fruit",
                  "Tender Coconut",
                  "Foxtail Millet(Navane)",
                  "Green Peas",
                  "Tapioca",
                  "Amphophalus",
                  "Ashgourd",
                  "Amaranthus",
                  "Mango",
                  "Black Pepper",
                  "Mango (Raw-Ripe)",
                  "Coconut",
                  "Rubber",
                  "Copra",
                  "Coconut Oil",
                  "Coconut Seed",
                  "Cowpea (Lobia/Karamani)",
                  "Lime",
                  "Pepper Ungarbled",
                  "Duster Beans",
                  "Coffee",
                  "Mint(Pudina)",
                  "Gur(Jaggery)",
                  "Chrysanthemum(Loose)",
                  "Marigold(Calcutta)",
                  "Betal Leaves",
                  "Hen",
                  "Jack Fruit",
                  "Fish",
                  "Amla(Nelli Kai)",
                  "Rat Tail Radish (Mogari)",
                  "Season Leaves",
                  "Squash(Chappal Kadoo)",
                  "Moath Dal",
                  "Taramira",
                  "Barley (Jau)",
                  "Soanf",
                  "Cashewnuts",
                  "T.v. Cumbu",
                  "Turmeric",
                  "Ragi (Finger Millet)",
                  "Paddy(Dhan)(Basmati)",
                  "Arhar Dal(Tur Dal)",
                  "Bengal Gram Dal (Chana Dal)",
                  "Black Gram Dal (Urd Dal)",
                  "Green Gram Dal (Moong Dal)",
                  "Lentil (Masur)(Whole)",
                  "Masur Dal",
                  "Ghee",
                  "Peas(Dry)",
                  "Linseed",
                  "Jute",
                  "Tomato",
                  "Tomato",
                  "Black Gram (Urd Beans)(Whole)",
                  "Lemon",
                  "Jowar(Sorghum)",
                  "Bengal Gram(Gram)(Whole)",
                  "Paddy(Dhan)(Common)",
                  "Maize",
                  "Apple",
                  "Banana - Green",
                  "Bhindi(Ladies Finger)",
                  "Bitter Gourd",
                  "Bottle Gourd",
                  "Brinjal",
                  "Cabbage",
                  "Capsicum",
                  "Carrot",
                  "Cauliflower",
                  "Chikoos(Sapota)",
                  "Coriander(Leaves)",
                  "Cucumbar(Kheera)",
                  "Garlic",
                  "Ginger(Green)",
                  "Grapes",
                  "Green Chilli",
                  "",
                  "Karbuja(Musk Melon)",
                  " Khol",
                  "Little Gourd (Kundru)",
                  "Methi(Leaves)",
                  "Mousambi(Sweet Lime)",
                  "Onion",
                  "Orange",
                  "Papaya (Raw)",
                  "Peas Wet",
                  "Pomegranate",
                  "Potato",
                  "Pumpkin",
                  "Raddish",
                  "Sweet Potato",
                  "Tinda",
                  "Water Melon",
                  "Soyabean",
                  "Cotton",
                  "Cummin Seed(Jeera)",
                  "Groundnut",
                  "Sesamum(Sesame",
                  "Gingelly",
                  "Til)",
                  "Wheat",
                  "Arhar (Tur/Red Gram)(Whole)",
                  "Bajra(Pearl Millet/Cumbu)",
                  "Green Gram (Moong)(Whole)",
                  "Kabuli Chana(Chickpeas-White)",
                  "Methi Seeds",
                  "Mustard",
                  "Castor Seed",
                  "Guar Seed(Cluster Beans Seed)",
                  "Isabgul (Psyllium)",
                  "Onion Green",
                  "Corriander Seed",
                  "Dry Chillies",
                  "Ground Nut Seed",
                  "Cluster Beans",
                  "Beetroot",
                  "Cowpea(Veg)",
                  "Drumstick",
                  "Elephant Yam (Suran)",
                  "French Beans (Frasbean)",
                  "Indian Beans (Seam)",
                  "Pegeon Pea (Arhar Fali)",
                  "Pointed Gourd (Parval)",
                  "Ridge Gourd(Tori)",
                  "Surat Beans (Papadi)",
                  "Turmeric (Raw)",
                  "Yam (Ratalu)",
                  "Spinach",
                  "Banana",
                  "Ber(Zizyphus/Borehannu)",
                  "Ginger(Dry)",
                  "Guava",
                  "Kinnow",
                  "Turnip",
                  "Leafy Vegetable",
                  "Papaya",
                  "Peas Cod",
                  "Pineapple",
                  "Mashrooms",
                  "Colacasia",
                  "Field Pea",
                  "Dalda",
                  "Mahua",
                  "Mustard Oil",
                  "Rice",
                  "Sugar",
                  "Wheat Atta",
                  "White Peas",
                  "Beans",
                  "Chapparad Avare",
                  "Chilly Capsicum",
                  "Green Avare (w)",
                  "Seemebadnekai",
                  "Snake Gourd",
                  "Suvarna Gadde",
                  "Sweet Pumpkin",
                  "Kulthi(Horse Gram)",
                  "Bunch Beans",
                  "Thondekai",
                  "Arecanut(Betelnut/Supari)",
                  "Tamarind Seed",
                  "Tamarind Fruit",
                  "Tender Coconut",
                  "Foxtail Millet(Navane)",
                  "Green Peas",
                  "Tapioca",
                  "Amphophalus",
                  "Ashgourd",
                  "Amaranthus",
                  "Mango",
                  "Black Pepper",
                  "Mango (Raw-Ripe)",
                  "Coconut",
                  "Rubber",
                  "Copra",
                  "Coconut Oil",
                  "Coconut Seed",
                  "Chili Red",
                  "Cowpea (Lobia/Karamani)",
                  "Lime",
                  "Pepper Ungarbled",
                  "Duster Beans",
                  "Coffee",
                  "Mint(Pudina)",
                  "Gur(Jaggery)",
                  "Chrysanthemum(Loose)",
                  "Marigold(Calcutta)",
                  "Betal Leaves",
                  "Hen",
                  "Jack Fruit",
                  "Fish",
                  "Amla(Nelli Kai)",
                  "Rat Tail Radish (Mogari)",
                  "Season Leaves",
                  "Squash(Chappal Kadoo)",
                  "Moath Dal",
                  "Taramira",
                  "Barley (Jau)",
                  "Soanf",
                  "Cashewnuts",
                  "T.v. Cumbu",
                  "Turmeric",
                  "Ragi (Finger Millet)",
                  "Paddy(Dhan)(Basmati)",
                  "Arhar Dal(Tur Dal)",
                  "Bengal Gram Dal (Chana Dal)",
                  "Black Gram Dal (Urd Dal)",
                  "Green Gram Dal (Moong Dal)",
                  "Lentil (Masur)(Whole)",
                  "Masur Dal",
                  "Ghee",
                  "Peas(Dry)",
                  "Linseed",
                  "Jute"
                ],
ch = '%20'
list2 = []
for wor in items:
    wor = wor.replace(" ",ch)
    list2.append(wor)
print(list2)

